test_projects_public:
    resource: "@TestProjectsBundle/Resources/config/routing.yml"
    prefix: /

test_projects_api:
    resource: "@TestProjectsBundle/Resources/config/routing_api.yml"
    prefix: /api
